package com.example.corda.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme (z Twojego pliku colors.xml)
val md_theme_light_primary = Color(0xFF28638A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF004B70)
val md_theme_light_secondary = Color(0xFF50606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD3E5F6)
val md_theme_light_onSecondaryContainer = Color(0xFF384956)
val md_theme_light_tertiary = Color(0xFF65587B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBDCFF)
val md_theme_light_onTertiaryContainer = Color(0xFF4D4162)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF7F9FF)
val md_theme_light_onBackground = Color(0xFF181C20)
val md_theme_light_surface = Color(0xFFF7F9FF)
val md_theme_light_onSurface = Color(0xFF181C20)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41474D)
val md_theme_light_outline = Color(0xFF72787E)

// Dark Theme (wygenerowane na podstawie Twoich wartości 'Inverse' i akcentów)
val md_theme_dark_primary = Color(0xFF96CCF8) // md_theme_inversePrimary
val md_theme_dark_onPrimary = Color(0xFF00344F)
val md_theme_dark_primaryContainer = Color(0xFF004B70)
val md_theme_dark_onPrimaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_secondary = Color(0xFFB7C9D9)
val md_theme_dark_onSecondary = Color(0xFF22323F)
val md_theme_dark_secondaryContainer = Color(0xFF384956)
val md_theme_dark_onSecondaryContainer = Color(0xFFD3E5F6)
val md_theme_dark_tertiary = Color(0xFFCFC0E8)
val md_theme_dark_onTertiary = Color(0xFF362B4B)
val md_theme_dark_tertiaryContainer = Color(0xFF4D4162)
val md_theme_dark_onTertiaryContainer = Color(0xFFEBDCFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF181C20) // md_theme_onBackground (jako tło)
val md_theme_dark_onBackground = Color(0xFFE0E3E8)
val md_theme_dark_surface = Color(0xFF101417)
val md_theme_dark_onSurface = Color(0xFFE0E3E8)
val md_theme_dark_surfaceVariant = Color(0xFF41474D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)